services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    container_name: pgvector-container
    environment:
      - 'POSTGRES_DB=chat-engine-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=chat-engine-user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3.2
volumes:
  ollama: {}  # Define the volume here